// lib/main.dart
//
// App entry point. main() is async because three I/O operations must finish
// before the app is allowed to show anything: finding where to store files,
// opening the Isar database, and loading SharedPreferences. Both results are
// then handed to Riverpod so every provider that needs them gets the real,
// already-ready object instead of an empty placeholder.

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:isar_community/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'core/isar_provider.dart';
import 'core/prefs_provider.dart';
import 'data/job_cache.dart';
import 'router/app_router.dart';

Future<void> main() async {
  // Must be the very first line. Sets up the bridge between Dart and the real
  // device. Without this, any call that talks to the phone (finding folders,
  // opening databases) would throw immediately.
  WidgetsFlutterBinding.ensureInitialized();

  // Asks the device: where am I allowed to save files for this app?
  final dir = await getApplicationDocumentsDirectory();

  // Opens (or creates, on first run) the actual Isar database file inside
  // that folder. JobCacheSchema is auto-generated by build_runner from the
  // @collection class in job_cache.dart.
  final isar = await Isar.open(
    [JobCacheSchema],
    directory: dir.path,
  );

  // Loads the device's simple key-value store, used for remembering small
  // settings like the last selected filter chip.
  final prefs = await SharedPreferences.getInstance();

  runApp(
    ProviderScope(
      overrides: [
        // Fills the empty isarProvider placeholder with the real, opened
        // database, so any code reading isarProvider from now on gets the
        // working instance instead of the "throw" placeholder.
        isarProvider.overrideWithValue(isar),

        // Same idea, for the real SharedPreferences instance.
        prefsProvider.overrideWithValue(prefs),
      ],
      // Only now, once both real instances are in place, does the visible
      // app actually start.
      child: const CareerHubApp(),
    ),
  );
}

// The root widget of the app. Sets up the overall MaterialApp — theme, dark
// mode, and the router that decides which screen is shown.
class CareerHubApp extends StatelessWidget {
  const CareerHubApp({super.key});

  // The single seed colour every other colour in the app's theme is
  // generated from, for both light and dark mode.
  static const Color _seed = Color(0xFF15803D);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'CareerHub',
      // Hides the red "DEBUG" banner in the corner during development.
      debugShowCheckedModeBanner: false,
      // Hands navigation control over to GoRouter instead of Flutter's
      // default single-screen setup.
      routerConfig: appRouter,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: _seed),
        useMaterial3: true,
      ),
      darkTheme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: _seed,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
      // Automatically follows the device's system-wide light/dark setting.
      themeMode: ThemeMode.system,
    );
  }
}